
export const initialState = {
  isFetchingOne: false,
  isFetchingList: false,
  isCreating: false,
  workspaces: [],
  workspace: null,
};

export const actionTypes = {
  CREATE_WORKSPACE_START: 'CREATE_WORKSPACE_START',
  CREATE_WORKSPACE_SUCCESS: 'CREATE_WORKSPACE_SUCCESS',
  GET_WORKSPACES_START: 'GET_WORKSPACES_START',
  GET_WORKSPACES_SUCCESS: 'GET_WORKSPACES_SUCCESS',
  GET_WORKSPACE_START: 'GET_WORKSPACE_START',
  GET_WORKSPACE_SUCCESS: 'GET_WORKSPACE_SUCCESS',
  CLEAR_WORKSPACES: 'CLEAR_WORKSPACES',
  CLEAR_WORKSPACE: 'CLEAR_WORKSPACE',
};
